function H = electronHamiltonian(omega_1 , omega_2, exchange, dipolar_tensor)

    s_x = [[0,0.5];[0.5,0]] ;
    s_y = [[0,-0.5i];[0.5i,0]] ;
    s_z = [[0.5,0];[0,-0.5]] ;
    id = eye(2) ;
    
    H = kron((omega_1(1)*s_x + omega_1(2)*s_y + omega_1(3)*s_z), id) ...
        + kron(id, (omega_2(1)*s_x + omega_2(2)*s_y + omega_2(3)*s_z)) ...
        + (2.0*exchange + dipolar_tensor(1,1)) * kron(s_x,s_x) ...
        + (2.0*exchange + dipolar_tensor(2,2)) * kron(s_y,s_y) ...
        + (2.0*exchange + dipolar_tensor(3,3)) * kron(s_z,s_z) ...
        + dipolar_tensor(1,2) * kron(s_x,s_y) + dipolar_tensor(2,1) * kron(s_y,s_x) ...
        + dipolar_tensor(1,3) * kron(s_x,s_z) + dipolar_tensor(3,1) * kron(s_z,s_x) ...
        + dipolar_tensor(2,3) * kron(s_y,s_z) + dipolar_tensor(3,2) * kron(s_z,s_y) ;
    
end